In [15]:
from pydataset import data


import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [10]:


data('voteincome', show_doc=True)

#data('voteincome')

voteincome

PyDataset Documentation (adopted from R Documentation. The displayed examples are in R)

## Sample Turnout and Demographic Data from the 2000 Current Population Survey

### Description

This data set contains turnout and demographic data from a sample of
respondents to the 2000 Current Population Survey (CPS). The states
represented are South Carolina and Arkansas. The data represent only a sample
and results from this example should not be used in publication.

### Usage

    data(voteincome)

### Format

A data frame containing 7 variables ("state", "year", "vote", "income",
"education", "age", "female") and 1500 observations.

`state`

a factor variable with levels equal to "AR" (Arkansas) and "SC" (South
Carolina)

`year`

an integer vector

`vote`

an integer vector taking on values "1" (Voted) and "0" (Did Not Vote)

`income`

an integer vector ranging from "4" (Less than \$5000) to "17" (Greater than
\$75000) denoting family income. See the CPS codebook for more information on
variable coding

`education`

an integer vector ranging from "1" (Less than High School Education) to "4"
(More than a College Education). See the CPS codebook for more information on
variable coding

`age`

an integer vector ranging from "18" to "85"

`female`

an integer vector taking on values "1" (Female) and "0" (Male)

### Source

Census Bureau Current Population Survey

### References

http://www.census.gov/cps

In [11]:
df = data('voteincome')

In [12]:
df = df.drop(columns = ['state', 'year'])

In [13]:
df

      vote  income  education  age  female
1        1       9          2   73       0
2        1      11          2   24       0
3        0      12          2   24       1
4        1      16          4   40       0
5        1      10          4   85       1
6        1      12          3   78       1
7        0      14          4   31       0
8        1      10          1   75       0
9        1      17          2   54       0
10       1       8          1   78       0
11       1      15          3   71       0
12       1      13          3   40       1
13       1      10          2   46       0
14       1       9          2   71       1
15       1       5          2   20       1
16       1      10          3   60       0
17       1       8          2   45       0
18       1      14          1   45       0
19       1      14          2   20       1
20       1       6          1   77       0
21       0      17          2   50       1
22       1      12          2   65       0
23       1       6          1   84       1
24       1      13          2   56       1
25       1       7          1   56       0
26       1      15          4   44       0
27       1      16          2   50       0
28       1       8          2   31       1
29       1      16          4   64       0
30       1      10          1   80       0
31       0       9          1   37       0
32       1      16          2   55       1
33       1      16          2   37       0
34       1      11          2   53       1
35       1       9          3   50       0
36       1       7          4   41       0
37       1       9          2   56       0
38       1      11          2   42       0
39       1      17          4   35       1
40       1       5          2   77       1
41       1       5          1   85       1
42       1       6          3   79       1
43       0       4          1   23       1
44       1      17          4   62       0
45       1       8          2   45       0
46       1       8          3   71       0
47       1      17          4   59       0
48       1      13          4   25       1
49       1      10          3   66       0
50       1       4          3   36       1
51       0      16          3   28       0
52       1      17          4   63       0
53       0       9          1   63       0
54       1       7          2   85       1
55       0       4          2   23       1
56       1      16          2   18       1
57       1      16          4   59       0
58       1      10          2   44       1
59       1       8          2   54       1
60       1      15          4   46       1
61       1      16          3   29       1
62       0      10          2   21       0
63       1      16          3   58       0
64       1      12          3   19       1
65       0       7          2   50       1
66       1      16          2   67       1
67       0       4          2   30       0
68       1       9          2   69       0
69       1      13          3   30       0
70       0      10          4   47       1
71       1       9          2   62       1
72       0      11          2   35       0
73       1       9          3   44       1
74       1       6          2   25       1
75       1      15          3   43       1
76       1      13          3   39       1
77       1      12          2   80       0
78       1      12          2   81       1
79       1       4          1   85       1
80       1      17          3   28       1
81       0      15          2   49       1
82       1      16          3   29       1
83       1      16          4   50       0
84       1       4          2   61       0
85       1      10          2   34       0
...    ...     ...        ...  ...     ...
1416     1       8          1   74       0
1417     1       4          2   45       1
1418     1      17          4   45       0
1419     1      17          4   63       0
1420     1      16          2   41       0
1421     1      17          4   40       1
1422     1      17          4   48       0
1423     1      11          4   28       1
1424     1      11          1   55       0
1425     1      10          2   72       1
1426     1      17          4   43       1
1427     1      17          4   37       1
1428     1      17          4   55       1
1429     1      11          1   75       1
1430     1      17          4   49       0
1431     0      11          2   29       1
1432     1      13          2   40       0
1433     1       7          2   62       1
1434     1       9          2   41       1
1435     1       7          2   40       1
1436     1      12          1   60       1
1437     1      16          2   50       1
1438     1      11          4   38       1
1439     0       8          2   19       0
1440     0       7          1   73       0
1441     1      15          4   82       0
1442     1      16          2   56       1
1443     1      17          2   53       0
1444     1      15          4   40       0
1445     1      14          2   59       1
1446     1      16          3   33       0
1447     1       5          1   64       0
1448     1      14          4   32       1
1449     1      17          4   56       1
1450     1      16          4   50       0
1451     1      10          1   80       0
1452     1       8          1   46       1
1453     1      16          4   37       0
1454     1      17          4   40       1
1455     1       7          1   82       0
1456     1      15          4   62       0
1457     1      13          4   34       1
1458     1      17          4   50       1
1459     1      16          4   44       0
1460     1      15          3   68       0
1461     1      14          3   25       1
1462     1      11          1   23       1
1463     0      17          4   43       0
1464     1      13          3   38       0
1465     1      13          3   23       1
1466     1       5          2   47       1
1467     1      16          4   55       1
1468     1       5          2   45       0
1469     0       9          2   20       1
1470     1      16          3   42       1
1471     1       8          1   54       0
1472     1      11          1   76       0
1473     0       9          1   78       0
1474     1      16          4   37       1
1475     1      15          3   46       0
1476     1      12          2   26       1
1477     1      17          3   43       1
1478     0      15          2   36       1
1479     1      16          2   37       0
1480     1      16          4   50       1
1481     1      17          3   57       0
1482     1       5          3   24       1
1483     1      13          3   19       1
1484     0       9          3   51       1
1485     1      13          2   53       1
1486     1      17          4   48       1
1487     1      17          4   63       1
1488     0       9          2   81       1
1489     1      17          2   35       0
1490     1      10          4   84       0
1491     1      16          2   57       0
1492     1      11          4   28       1
1493     0       8          1   62       1
1494     1       5          2   50       1
1495     1      15          2   51       1
1496     1      17          4   53       1
1497     1      10          2   24       0
1498     1      12          3   46       0
1499     0      12          1   79       1
1500     1       9          1   36       1

[1500 rows x 5 columns]

In [16]:
df.dropna(inplace=True) # handle missing age values

X = df[['income','education','age','female']]
y = df[['vote']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .30, random_state = 123)

X_train.head()

      income  education  age  female
892       17          4   38       1
1386      15          3   47       1
1187      17          2   85       1
490       11          3   76       1
1237      12          2   19       0

## K = 4

In [17]:
knn = KNeighborsClassifier(n_neighbors=4, weights='uniform')

In [18]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [19]:
y_pred = knn.predict(X_train)

In [20]:
y_pred_proba = knn.predict_proba(X_train)

In [21]:
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))

Accuracy of KNN classifier on training set: 0.88

In [22]:
print(confusion_matrix(y_train, y_pred))

[[ 99  55]
 [ 69 827]]

In [24]:
print(classification_report(y_train, y_pred))
print('Accuracy of KNN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))

              precision    recall  f1-score   support

           0       0.59      0.64      0.61       154
           1       0.94      0.92      0.93       896

    accuracy                           0.88      1050
   macro avg       0.76      0.78      0.77      1050
weighted avg       0.89      0.88      0.88      1050

Accuracy of KNN classifier on test set: 0.81

## K = 3

In [26]:
knn3 = KNeighborsClassifier(n_neighbors=3, weights='uniform')

In [27]:
knn3.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [28]:
y_pred = knn3.predict(X_train)
y_pred_proba = knn3.predict_proba(X_train)

In [29]:
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn3.score(X_train, y_train)))

Accuracy of KNN classifier on training set: 0.91

In [30]:
print(confusion_matrix(y_train, y_pred))

[[ 87  67]
 [ 24 872]]

In [38]:
print(classification_report(y_train, y_pred))
print('Accuracy of KNN classifier on test set: {:.2f}'
     .format(knn3.score(X_test, y_test)))

              precision    recall  f1-score   support

           0       0.67      0.99      0.80       154
           1       1.00      0.92      0.96       896

    accuracy                           0.93      1050
   macro avg       0.84      0.96      0.88      1050
weighted avg       0.95      0.93      0.93      1050

Accuracy of KNN classifier on test set: 0.82

## K = 2

In [32]:
knn2 = KNeighborsClassifier(n_neighbors=2, weights='uniform')

In [33]:
knn2.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [34]:
y_pred = knn2.predict(X_train)
y_pred_proba = knn2.predict_proba(X_train)

In [35]:
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn2.score(X_train, y_train)))

Accuracy of KNN classifier on training set: 0.93

In [36]:
print(confusion_matrix(y_train, y_pred))

[[153   1]
 [ 74 822]]

In [39]:
print(classification_report(y_train, y_pred))
print('Accuracy of KNN classifier on test set: {:.2f}'
     .format(knn2.score(X_test, y_test)))

              precision    recall  f1-score   support

           0       0.67      0.99      0.80       154
           1       1.00      0.92      0.96       896

    accuracy                           0.93      1050
   macro avg       0.84      0.96      0.88      1050
weighted avg       0.95      0.93      0.93      1050

Accuracy of KNN classifier on test set: 0.79

## K = 1

In [40]:
knn1 = KNeighborsClassifier(n_neighbors=1, weights='uniform')

In [41]:
knn1.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [42]:
y_pred = knn1.predict(X_train)
y_pred_proba = knn1.predict_proba(X_train)

In [43]:
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn1.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))

Accuracy of KNN classifier on training set: 0.98
[[144  10]
 [ 13 883]]

In [44]:
print(classification_report(y_train, y_pred))
print('Accuracy of KNN classifier on test set: {:.2f}'
     .format(knn1.score(X_test, y_test)))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93       154
           1       0.99      0.99      0.99       896

    accuracy                           0.98      1050
   macro avg       0.95      0.96      0.96      1050
weighted avg       0.98      0.98      0.98      1050

Accuracy of KNN classifier on test set: 0.84

In [48]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93       154
           1       0.99      0.99      0.99       896

    accuracy                           0.98      1050
   macro avg       0.95      0.96      0.96      1050
weighted avg       0.98      0.98      0.98      1050

In [50]:
from sklearn import __version__
__version__

'0.21.2'